// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/cantabular"
	"github.com/ONSdigital/dp-cantabular-csv-exporter/service"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"io"
	"sync"
)

var (
	lockCantabularClientMockChecker                     sync.RWMutex
	lockCantabularClientMockCheckerAPIExt               sync.RWMutex
	lockCantabularClientMockStaticDatasetQueryStreamCSV sync.RWMutex
)

// Ensure, that CantabularClientMock does implement service.CantabularClient.
// If this is not the case, regenerate this file with moq.
var _ service.CantabularClient = &CantabularClientMock{}

// CantabularClientMock is a mock implementation of service.CantabularClient.
//
//     func TestSomethingThatUsesCantabularClient(t *testing.T) {
//
//         // make and configure a mocked service.CantabularClient
//         mockedCantabularClient := &CantabularClientMock{
//             CheckerFunc: func(in1 context.Context, in2 *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//             CheckerAPIExtFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the CheckerAPIExt method")
//             },
//             StaticDatasetQueryStreamCSVFunc: func(ctx context.Context, req cantabular.StaticDatasetQueryRequest, consume func(ctx context.Context, r io.Reader) error) (int32, error) {
// 	               panic("mock out the StaticDatasetQueryStreamCSV method")
//             },
//         }
//
//         // use mockedCantabularClient in code that requires service.CantabularClient
//         // and then make assertions.
//
//     }
type CantabularClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(in1 context.Context, in2 *healthcheck.CheckState) error

	// CheckerAPIExtFunc mocks the CheckerAPIExt method.
	CheckerAPIExtFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// StaticDatasetQueryStreamCSVFunc mocks the StaticDatasetQueryStreamCSV method.
	StaticDatasetQueryStreamCSVFunc func(ctx context.Context, req cantabular.StaticDatasetQueryRequest, consume func(ctx context.Context, r io.Reader) error) (int32, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// In1 is the in1 argument value.
			In1 context.Context
			// In2 is the in2 argument value.
			In2 *healthcheck.CheckState
		}
		// CheckerAPIExt holds details about calls to the CheckerAPIExt method.
		CheckerAPIExt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// StaticDatasetQueryStreamCSV holds details about calls to the StaticDatasetQueryStreamCSV method.
		StaticDatasetQueryStreamCSV []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req cantabular.StaticDatasetQueryRequest
			// Consume is the consume argument value.
			Consume func(ctx context.Context, r io.Reader) error
		}
	}
}

// Checker calls CheckerFunc.
func (mock *CantabularClientMock) Checker(in1 context.Context, in2 *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("CantabularClientMock.CheckerFunc: method is nil but CantabularClient.Checker was just called")
	}
	callInfo := struct {
		In1 context.Context
		In2 *healthcheck.CheckState
	}{
		In1: in1,
		In2: in2,
	}
	lockCantabularClientMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockCantabularClientMockChecker.Unlock()
	return mock.CheckerFunc(in1, in2)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedCantabularClient.CheckerCalls())
func (mock *CantabularClientMock) CheckerCalls() []struct {
	In1 context.Context
	In2 *healthcheck.CheckState
} {
	var calls []struct {
		In1 context.Context
		In2 *healthcheck.CheckState
	}
	lockCantabularClientMockChecker.RLock()
	calls = mock.calls.Checker
	lockCantabularClientMockChecker.RUnlock()
	return calls
}

// CheckerAPIExt calls CheckerAPIExtFunc.
func (mock *CantabularClientMock) CheckerAPIExt(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerAPIExtFunc == nil {
		panic("CantabularClientMock.CheckerAPIExtFunc: method is nil but CantabularClient.CheckerAPIExt was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	lockCantabularClientMockCheckerAPIExt.Lock()
	mock.calls.CheckerAPIExt = append(mock.calls.CheckerAPIExt, callInfo)
	lockCantabularClientMockCheckerAPIExt.Unlock()
	return mock.CheckerAPIExtFunc(ctx, state)
}

// CheckerAPIExtCalls gets all the calls that were made to CheckerAPIExt.
// Check the length with:
//     len(mockedCantabularClient.CheckerAPIExtCalls())
func (mock *CantabularClientMock) CheckerAPIExtCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	lockCantabularClientMockCheckerAPIExt.RLock()
	calls = mock.calls.CheckerAPIExt
	lockCantabularClientMockCheckerAPIExt.RUnlock()
	return calls
}

// StaticDatasetQueryStreamCSV calls StaticDatasetQueryStreamCSVFunc.
func (mock *CantabularClientMock) StaticDatasetQueryStreamCSV(ctx context.Context, req cantabular.StaticDatasetQueryRequest, consume func(ctx context.Context, r io.Reader) error) (int32, error) {
	if mock.StaticDatasetQueryStreamCSVFunc == nil {
		panic("CantabularClientMock.StaticDatasetQueryStreamCSVFunc: method is nil but CantabularClient.StaticDatasetQueryStreamCSV was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Req     cantabular.StaticDatasetQueryRequest
		Consume func(ctx context.Context, r io.Reader) error
	}{
		Ctx:     ctx,
		Req:     req,
		Consume: consume,
	}
	lockCantabularClientMockStaticDatasetQueryStreamCSV.Lock()
	mock.calls.StaticDatasetQueryStreamCSV = append(mock.calls.StaticDatasetQueryStreamCSV, callInfo)
	lockCantabularClientMockStaticDatasetQueryStreamCSV.Unlock()
	return mock.StaticDatasetQueryStreamCSVFunc(ctx, req, consume)
}

// StaticDatasetQueryStreamCSVCalls gets all the calls that were made to StaticDatasetQueryStreamCSV.
// Check the length with:
//     len(mockedCantabularClient.StaticDatasetQueryStreamCSVCalls())
func (mock *CantabularClientMock) StaticDatasetQueryStreamCSVCalls() []struct {
	Ctx     context.Context
	Req     cantabular.StaticDatasetQueryRequest
	Consume func(ctx context.Context, r io.Reader) error
} {
	var calls []struct {
		Ctx     context.Context
		Req     cantabular.StaticDatasetQueryRequest
		Consume func(ctx context.Context, r io.Reader) error
	}
	lockCantabularClientMockStaticDatasetQueryStreamCSV.RLock()
	calls = mock.calls.StaticDatasetQueryStreamCSV
	lockCantabularClientMockStaticDatasetQueryStreamCSV.RUnlock()
	return calls
}
