// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"
)

// GeneratorMock is a mock implementation of handler.Generator.
//
// 	func TestSomethingThatUsesGenerator(t *testing.T) {
//
// 		// make and configure a mocked handler.Generator
// 		mockedGenerator := &GeneratorMock{
// 			NewPSKFunc: func() ([]byte, error) {
// 				panic("mock out the NewPSK method")
// 			},
// 			NewUUIDFunc: func() string {
// 				panic("mock out the NewUUID method")
// 			},
// 		}
//
// 		// use mockedGenerator in code that requires handler.Generator
// 		// and then make assertions.
//
// 	}
type GeneratorMock struct {
	// NewPSKFunc mocks the NewPSK method.
	NewPSKFunc func() ([]byte, error)

	// NewUUIDFunc mocks the NewUUID method.
	NewUUIDFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// NewPSK holds details about calls to the NewPSK method.
		NewPSK []struct {
		}
		// NewUUID holds details about calls to the NewUUID method.
		NewUUID []struct {
		}
	}
	lockNewPSK  sync.RWMutex
	lockNewUUID sync.RWMutex
}

// NewPSK calls NewPSKFunc.
func (mock *GeneratorMock) NewPSK() ([]byte, error) {
	if mock.NewPSKFunc == nil {
		panic("GeneratorMock.NewPSKFunc: method is nil but Generator.NewPSK was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNewPSK.Lock()
	mock.calls.NewPSK = append(mock.calls.NewPSK, callInfo)
	mock.lockNewPSK.Unlock()
	return mock.NewPSKFunc()
}

// NewPSKCalls gets all the calls that were made to NewPSK.
// Check the length with:
//     len(mockedGenerator.NewPSKCalls())
func (mock *GeneratorMock) NewPSKCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNewPSK.RLock()
	calls = mock.calls.NewPSK
	mock.lockNewPSK.RUnlock()
	return calls
}

// NewUUID calls NewUUIDFunc.
func (mock *GeneratorMock) NewUUID() string {
	if mock.NewUUIDFunc == nil {
		panic("GeneratorMock.NewUUIDFunc: method is nil but Generator.NewUUID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNewUUID.Lock()
	mock.calls.NewUUID = append(mock.calls.NewUUID, callInfo)
	mock.lockNewUUID.Unlock()
	return mock.NewUUIDFunc()
}

// NewUUIDCalls gets all the calls that were made to NewUUID.
// Check the length with:
//     len(mockedGenerator.NewUUIDCalls())
func (mock *GeneratorMock) NewUUIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNewUUID.RLock()
	calls = mock.calls.NewUUID
	mock.lockNewUUID.RUnlock()
	return calls
}
