// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-cantabular-csv-exporter/handler"
)

// Ensure, that S3ClientMock does implement handler.S3Client.
// If this is not the case, regenerate this file with moq.
var _ handler.S3Client = &S3ClientMock{}

// S3ClientMock is a mock implementation of handler.S3Client.
//
// 	func TestSomethingThatUsesS3Client(t *testing.T) {
//
// 		// make and configure a mocked handler.S3Client
// 		mockedS3Client := &S3ClientMock{
// 		}
//
// 		// use mockedS3Client in code that requires handler.S3Client
// 		// and then make assertions.
//
// 	}
type S3ClientMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
