// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-cantabular-csv-exporter/event"
)

// Ensure, that CantabularClientMock does implement event.CantabularClient.
// If this is not the case, regenerate this file with moq.
var _ event.CantabularClient = &CantabularClientMock{}

// CantabularClientMock is a mock implementation of event.CantabularClient.
//
//     func TestSomethingThatUsesCantabularClient(t *testing.T) {
//
//         // make and configure a mocked event.CantabularClient
//         mockedCantabularClient := &CantabularClientMock{
//         }
//
//         // use mockedCantabularClient in code that requires event.CantabularClient
//         // and then make assertions.
//
//     }
type CantabularClientMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
